### PR TITLE
Add wandb example

### PR DESCRIPTION
**Pull request by vwxyzjn**

### CODE REVIEW

**Comment by araffin** [comment]
Hello,
thanks for the PR, could also add a link in the readme?

**Comment by vwxyzjn** [comment]
@araffin  done :)

**Review by araffin — APPROVED** [review]
LGTM, thanks =)

**Comment by araffin** [comment]
Btw, could you do a PR that updates SB3 doc (and add a link to that colab notebook)?
Otherwise, I will do it ;)

**Comment by vwxyzjn** [comment]
Hey I was gonna do that, but actually is now working on a deeper integration. See https://wandb.ai/costa-huang/sb3/runs/kevxmgwt?workspace=user-costa-huang. And the code roughly looks like

```
import gym
from stable_baselines3 import PPO
from stable_baselines3.common.vec_env import DummyVecEnv
from wandb.integration.sb3 import WandbCallback

def make_env():
    env = gym.make("CartPole-v1")
    env = gym.wrappers.Monitor(env, f"videos", force=True)      # record videos
    env = gym.wrappers.RecordEpisodeStatistics(env) # record stats such as returns
    return env

config = {
    "policy_type": 'MlpPolicy',
    "total_timesteps": 25000
}

env = DummyVecEnv([make_env])
model = PPO(config['policy_type'], env, verbose=1, tensorboard_log=f"runs/ppo")
model.learn(total_timesteps=config['total_timesteps'],
    callback=WandbCallback(project="sb3", config=config))
```

**Comment by vwxyzjn** [comment]
See https://github.com/wandb/client/pull/2334 for instructions on how to run.

**Comment by araffin** [comment]
nice, thanks =), I was actually wondering where did the `from wandb.integration.sb3 import WandbCallback` came from.

**Comment by vwxyzjn** [comment]
Haha nice. Feel free to leave any comments. E.g. should the model uploading to be optional?

**Pull request merged**
